M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Mo 12 Sep 2022 11:49:22 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-12T11:49:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X147.213Y-44.454
X152.063Y-44.454
T2
X146.913Y-41.424
X152.363Y-41.424
T0
M30
